set lines 300
set pages 500
COLUMN size_factor FORMAT 9.0000
COLUMN SIZE_FOR_ESTIMATE FORMAT 999999
COLUMN BUFFERS_FOR_ESTIMATE FORMAT 99999999
COLUMN ESTD_PHYSICAL_READ_FACTOR FORMAT 9.0000
COLUMN ESTD_PHYSICAL_READS FORMAT 9999999999
COLUMN ESTD_PHYSICAL_READ_TIME FORMAT 9999999999
COLUMN ESTD_PCT_OF_DB_TIME_FOR_READS FORMAT 999.00

show parameters CACHE;

select size_factor, SIZE_FOR_ESTIMATE, BUFFERS_FOR_ESTIMATE,  ESTD_PHYSICAL_READ_FACTOR, ESTD_PHYSICAL_READS, ESTD_PHYSICAL_READ_TIME, ESTD_PCT_OF_DB_TIME_FOR_READS from v$db_cache_advice where name = 'DEFAULT' order by size_factor;
